controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  my_controller:
    type: my_controller/MyPositionController
    joint: pole2joint
    feedforward_gain_: 0.1
    use_feedforward: 1
    pid: { p: 10.0, i: 0.1, d: 0.01 }
