controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  my_controller:
    type: my_controller/MyPositionController
    joint: pole2joint
    feedforward_gain_: 3
    use_feedforward: 1
    pid: { p: 93.0, i: 1.8, d: 0.05 }
